Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-11"
  config.vm.box_version = "2302.0.2409"

  vm.provider "virtualbox" do |vb|
      vb.name = "Defender W11 2024"
      vb.cpus = 4
      vb.memory = 8192
    end
end
