Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Attacker Ubuntu 24.04"
    vb.cpus = 4
    vb.memory = "8192"
  end
end
