# Specifies the Vagrantfile version we're using. In this case, version 2.
Vagrant.configure("2") do |config|

  # Defines the virtual machine (VM) we'll be working with.
  # We're using the "bento/ubuntu-24.04" box, which provides a pre-configured Ubuntu 24.04 environment.
  config.vm.box = "bento/ubuntu-24.04"

  # Configures the network adapter for the VM. We're creating a private network adapter
  # and assigning a static IP address of "192.168.50.10" to the VM.
  config.vm.network "private_network", ip: "192.168.50.10"

  # Defines configuration specific to the VirtualBox provider.
  config.vm.provider "virtualbox" do |vb|

    # Sets the display name of the VM in the VirtualBox GUI.
    vb.name = "Attacker Ubuntu 24.04"

    # Allocates 4 virtual CPUs (cores) to the VM. 2 cores is a good minimum.
    vb.cpus = 4

    # This line assigns 8192 MB (or 8 GB) of memory to the VM. 2048 is a good minimum.
    vb.memory = "8192"
  end
end
